### ISSUE TITLE
Strange behavior in 'Post update' textarea focus when you post a particular type of comment. 

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#1229]
**Describe the bug**

Ok, you want to publish some new content.
You click *once* on the text box.
Perfect. You're now able to write your content and publish it.
However, if you comment u@bug at any post (must be a comment, not a post) the bug happens.
So you want to publish any other post.
Um click on the text box once and you're not able to write your content as in the first time. You need to click again. And some times one more time.
And finally you're able to write your message.

It will happen even in the comments field as well as the post box, and to every user that try to post something.

**To Reproduce**
https://www.dropbox.com/s/0ubaclpr5ejf1dz/buddyboss.mov?dl=0

**Screenshots**
https://www.dropbox.com/s/0ubaclpr5ejf1dz/buddyboss.mov?dl=0

**Support ticket links**
https://secure.helpscout.net/conversation/1167195211/73826?folderId=3701249

**Comment by amincdev** [comment]
As per @KartikSuthar this issue should be fixed by this one: https://github.com/buddyboss/buddyboss-platform/issues/927
Can you please confirm with customer for the same?

**Comment by fernandoacosta** [comment]
> As per @KartikSuthar this issue should be fixed by this one: #927
> Can you please confirm with customer for the same?

I'm following this thread because I'm looking for this solution for a few months. I've asked for both solutions. And this one is still happening.

![image](https://user-images.githubusercontent.com/7092808/90031260-6752bc00-dc93-11ea-84b9-6418c13bb50c.png)

After two comments with the content "@007" I need to click three times on the post form to focus on it. If I add 10 comments like this one, I'll need to click 11 times before post one update. 

Not just me, of course, but anyone with those particular comments on screen.

As you can see in the screenshot, the comments texts are "@007@007", however, I've typed just "@007" and the content duplicates after page refresh.

**Comment by amincdev** [comment]
I have added multiple comments same as you shared here. But still not able to replicate the issue: https://prnt.sc/tyv6j3
@KartikSuthar Can you please also check this?

**Comment by fernandoacosta** [comment]
After comment the as you made, the issue **is not on the comment system**, but in the "whats-new" form. There is a video here https://www.dropbox.com/s/0ubaclpr5ejf1dz/buddyboss.mov?dl=0

**Comment by amincdev** [comment]
@fernandoacosta Thank you for the video. I will try to replicate it.

**Comment by KartikSuthar** [comment]
@Anve-sri @fernandoacosta @amincdev 
I have checked for the issue with the latest version of the platform plugin in local as well on the demo site both and found that issue was fixed.
http://somup.com/cYjFIu6Gci

Can you please check with the latest version of the platform and inform me if you are still able to reproduce the issue.

**Comment by fernandoacosta** [comment]
> > As per @KartikSuthar this issue should be fixed by this one: #927
> > Can you please confirm with customer for the same?
> 
> I'm following this thread because I'm looking for this solution for a few months. I've asked for both solutions. And this one is still happening.
> 
> ![image](https://user-images.githubusercontent.com/7092808/90031260-6752bc00-dc93-11ea-84b9-6418c13bb50c.png)
> 
> After two comments with the content "@007" I need to click three times on the post form to focus on it. If I add 10 comments like this one, I'll need to click 11 times before post one update.
> 
> Not just me, of course, but anyone with those particular comments on screen.
> 
> As you can see in the screenshot, the comments texts are "@007@007", however, I've typed just "@007" and the content duplicates after page refresh.
> 
> It's your demo page. So there is no conflicts with my own plugins.
> 
> Thanks

Please, refer to this message
The bug isn't happening for email addresses, but for non existing/deleted users

**Comment by Anve-sri** [comment]
@KartikSuthar Please have a look https://www.loom.com/share/220ea1da968a490aa406edfb5886db53

**Comment by sourabhmatolia** [comment]
@mehulkaklotar 

Please take over this task.

**Couple issues explained in the video here:**
https://www.loom.com/share/929943575d604a80be6dcf1ae434856a

Thanks

**Comment by mehulkaklotar** [comment]
@sourabhmatolia There is an issue with atwho.js which is picking up `atwho-query` elements on the page when typing. So in comments when we enter wrong usernames and post it. it saved as atwho-query and and when you goto type activity or comment after that, it will fire requests for all those wrong usernames and creates problem. So I have fixed future comments saving atwho-query elements so it will be fixed for future posts and comments. but for the past or current comments it will be same issue.

**Comment by ankitguptaindia** [comment]
FYI- Removed ` can't reproduce` label as this is already has PR to test

**Comment by sourabhmatolia** [comment]
@fernandoacosta 


Issue created above is released in Buddyboss Platform v1.5.1.

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-1/

Please update the plugin to see the latest changes.

Thank you.
