### ISSUE TITLE
"Mark as read" notification on mobile issue

### ISSUE THREAD

**Issue by fabiomail** [buddyboss/buddyboss-platform#1534]
**Is your feature request related to a problem? Please describe.**
The new mark as read single notification button is not visible in mobile version, making it very difficult to be used. 

**Describe the solution you'd like**
On mobile, the button should be always visible so that users can simply tap and mark as read. 

Here a demo: https://drive.google.com/file/d/1SgsBmpFF8poAN14rYg2PyDg9af7Eukrj/view?usp=sharing

**Comment by AmineBAIK1** [comment]
Same issue here

**Comment by amincdev** [comment]
This issue is related to the theme and fixed in theme: https://github.com/buddyboss/buddyboss-theme/issues/1153

**Comment by fabiomail** [comment]
@amincdev the link is not working for me. Anyway, the issue I mentioned above is not actually solved in the latest release. Indeed, as you can see here: https://snipboard.io/2v71Wx.jpg

1. The "hide" icon on every single notification is not visible on mobile (it is meant for the desktop, with mouse hover) 
2. there is a lot of white space not properly used on the right column. It can be optimized.

I hope I was able to explain what I am trying to say... Thank you!

**Comment by amincdev** [comment]
@fabiomail Yes, Above mentioned link is from our theme repository which is not public.

> The "hide" icon on every single notification is not visible on mobile (it is meant for the desktop, with mouse hover)

This issue is fixed and it will be included in the next theme release.

> there is a lot of white space not properly used on the right column. It can be optimized.

This issue is also fixed in the theme and it will be included in the next theme release.

**Comment by fabiomail** [comment]
That's great @amincdev , thanks for your support!
