### ISSUE TITLE
 Missing Friend ID on group pages

### ISSUE THREAD

**Issue by shyamgudadhe** [buddyboss/buddyboss-platform#2558]
**Describe the bug**
We discover a bug on your Dev site between BuddyBoss Platform and BuddyPress Extended FriendShip
 ( https://www.buddyboss.com/resources/docs/integrations/buddypress-add-ons/buddypress-extended-friendship-request/), 
 The bug is in: wp-contentpluginsbuddyboss-platformbp-friendsbp-friends-template.php
 
**To Reproduce**
1. First install BuddyPress Extended Friendship Request plugin
https://www.buddyboss.com/resources/docs/integrations/buddypress-add-ons/buddypress-extended-friendship-request/
2. Then go to Group page, click on any group member tab
3. Click on any unfollow connect icon, add some text in "Send Request box" then

**Expected behavior**
It should be send request without any error

**Screenshots**

**Environment**
https://ibb.co/wsBgtm4

**Support ticket links**
https://secure.helpscout.net/conversation/1558954101/150307

Jira: [PROD-788]

[PROD-788]: https://buddyboss.atlassian.net/browse/PROD-788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by meetmakadiya** [comment]
@shyamwp14 
I can't replicate this with the latest version of the platform can you please check the attachment for reference and let me know if I miss anything.
https://www.loom.com/share/f6443aceeeed42e5841a0c2ad8d87184

**Comment by azanoni** [comment]
> @shyamwp14
> I can't replicate this with the latest version of the platform can you please check the attachment for reference and let me know if I miss anything.
> 
> https://www.loom.com/share/f6443aceeeed42e5841a0c2ad8d87184

It's easy to check please https://www.loom.com/share/a9d52917103441dfae9ac7bec8322718

**Comment by meetmakadiya** [comment]
@azanoni @shyamgudadhe 
I check with activate the plugin and deactivate plugin both scenarios so the issue is regarding the **BuddyPress Extended Friendship Request** plugin and plugin not update the code and fetch the old id from the button instead off **bp-item-id** so need to update the  **BuddyPress Extended Friendship Request** plugin code. please check to attach the video I try to explain it in detail.
Hope this will be helpful to you.
https://www.loom.com/share/d2952c169dcb480bae5b6dfb1e2b5969

**Comment by azanoni** [comment]
@meetmakadiya I understand your point but the problem is regarding that you have a wrong ID on groups member page, you should fix that because having multiple same ids isn't a good practice (like friends-0 in each same <a button) so I suggest that fix this using this code in bp-friends-template.php

![image](https://user-images.githubusercontent.com/21685626/132040273-ffc2a502-8ba9-469f-85c7-107e2835d6b6.png)

Full explanation after minute 2:20 here https://www.loom.com/share/9a6781ad48fe4abda03a57ca71c3900a

**Comment by harshalQA** [comment]
Not fixed: As Admin user Getting an error while sending a connection request to Members from a public group

Tested site URL: https://bb-app-platform.flywheelsites.com/wp-admin/

Note: I installed BuddyPress Extended Friendship Request plugin: https://www.buddyboss.com/resources/docs/integrations/buddypress-add-ons/buddypress-extended-friendship-request/

Video:
https://www.awesomescreenshot.com/video/5438427?key=4695d36109f24c32ea644ed9cdc822f7
