### ISSUE TITLE
Enhancement - Media/Documents

### ISSUE THREAD

**Issue by chetansatasiya** [buddyboss/buddyboss-platform#962]
### Suggestion Lists

- [x] https://buddyboss.slack.com/archives/C013JBN4GRJ/p1591194344021800
- [x] https://buddyboss.slack.com/archives/C013JBN4GRJ/p1591343566000400
- [x] https://buddyboss.slack.com/archives/C013JBN4GRJ/p1591095578017100
- [ ] When you upload only 1 media/document and if you wriite any text then it should be added to that photo/document description. - Reverted the code as it creating the issue - ❌ 
- [x] https://buddyboss.slack.com/archives/DCCR02FDY/p1592966485000300 - https://www.loom.com/share/fd3aab2df4014b93991a06a54c412e90
- [x] Remove the activity from activity parent if it's move to other document folder
- [x] https://github.com/buddyboss/buddyboss-platform/issues/51
- [x] https://github.com/buddyboss/buddyboss-platform/issues/344
- [x] https://github.com/buddyboss/buddyboss-platform/issues/1332

### Proof of all the Changes 
https://github.com/buddyboss/buddyboss-platform/pull/1129#issuecomment-724595950
https://github.com/buddyboss/buddyboss-platform/pull/1129#issuecomment-724598829

**Comment by ankitguptaindia** [comment]
@amincdev @chetansatasiya 

If any post has multiple images and the user removed any one image from the newly added option then that deleted image still appears in the popup when editing.

And sometimes it shows a broken link with undefined. https://i.imgur.com/PpqAcsx.jpg 

Refer for steps, How to reproduce - https://www.loom.com/share/0c907558f7ac455b8c164c1315064ff8

**Comment by ankitguptaindia** [comment]
@sourabhmatolia Inconsistency between photos and documents behavior. Please confirm if the current logic is intended.

**In documents, we are showing `More Options ` always and show options according to File Owner But for Media, We are showing `More Option` only when Media is uploaded by same user.**

Please refer for more details -  https://www.loom.com/share/44fd4f5372394b0188a13a4055dd39ff

**Comment by ankitguptaindia** [comment]
@chetansatasiya / @amincdev 

Documents are not getting Moved to Folder if the folder is created from Popup. 
Although the folder is created successfully but Files are not appearing there after moving from Activity comments.
Refer this video for more details- 
https://www.loom.com/share/074a5ceea66a49ebb9579ab86d06138a

----

After moving Documents/Media to any folder/Album.
Remaining  Documents/Media having a blank sidebar.

https://www.loom.com/share/4bf3591afdad454b9bf68a925c26bde6

----

**Comment by ankitguptaindia** [comment]
@amincdev 

Please style this message box when uploading documents in User's Documents area.
https://prnt.sc/vqka2u

----

**UX issue -** If user uploading documents to folder which is appearing at the time of upload then it should not allow the user to Done until user selects the folder OR create a new folder. 
If user change mind not to upload in any specific folder then he/she should click `Back` button and click Done button.

https://www.loom.com/share/df1fca5cbd4247119dd8caa96b3f2ae0

**Comment by chetansatasiya** [comment]
> @amincdev @chetansatasiya
> 
> **If any post has multiple images and the user removed any one image from the newly added option then that deleted image still appears in the popup when editing.**
> 
> And sometimes it shows a broken link with undefined. https://i.imgur.com/PpqAcsx.jpg
> 
> Refer for steps, How to reproduce -
> 
> https://www.loom.com/share/0c907558f7ac455b8c164c1315064ff8
> 
> **Deleting a photo from newly added delete option breaking `Load More` button on Photos page. https://i.imgur.com/zaqOorW.jpg**
> 
> Counts are not getting updated if deleting photos from newly added DELETE option.
> 
> https://www.loom.com/share/e7a4719ed240416ca6bdc7c0f25530a6

@ankitguptaindia This is fixed now 👍

**Comment by ankitguptaindia** [comment]
> > @amincdev @chetansatasiya
> > **If any post has multiple images and the user removed any one image from the newly added option then that deleted image still appears in the popup when editing.**
> > And sometimes it shows a broken link with undefined. https://i.imgur.com/PpqAcsx.jpg
> > Refer for steps, How to reproduce -
> > https://www.loom.com/share/0c907558f7ac455b8c164c1315064ff8
> > **Deleting a photo from newly added delete option breaking `Load More` button on Photos page. https://i.imgur.com/zaqOorW.jpg**
> > Counts are not getting updated if deleting photos from newly added DELETE option.
> > https://www.loom.com/share/e7a4719ed240416ca6bdc7c0f25530a6
> 
> @ankitguptaindia This is fixed now 👍

@chetansatasiya thanks plz merge in dev branch

**Comment by ankitguptaindia** [comment]
@amincdev 

**Media/Documents Uploader Popup issue -  When user creates multiples Subfolders then the breadcrumb looks broken.**
https://prnt.sc/vqksy8

------

**Suggestions for UX - Destination folder should show as selected when user uploading documents to specific folders.**

Refer for more details - https://www.loom.com/share/e708610b3d3f41c5a778407d959a5396

**Comment by ankitguptaindia** [comment]
@chetansatasiya  I found these 2 Critical Privacy bug if user moving files later by using the Move option available in More options.
Although it is hard to reproduce easily. Sharing de

Support user has 1 root folder `Fol-1` and 4 subfolders like sub-1.... Sub-5 in that root folder. Fol-1 has Privacy `Only me` so as per logic all subfolders and files under Fol-1 will also have privacy Only me.

Suppose User Moved a file to directly to any subfolder then later change the privacy of that file from activity.
When the user try to edit privacy system says - Edit Folder Privacy and open the popup to edit folder privacy.
After that when user change the privacy of Subfolder-5 then it also change the privacy to all other subfolders like Sub-4, Sub-3 and root Folder Fol-1.

All files under root folder and subfolder getting public.

https://www.loom.com/share/810a9b97b27b4b8898d3771697f897a4

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

When uploading Media files to activity, it shows some unexpected reponse like object object in popup https://prnt.sc/vr7a66

I noticed it happens when I use .ico files in media. 
Attaching files with this comment so you can test on your site.

[untitled folder.zip](https://github.com/buddyboss/buddyboss-platform/files/5607817/untitled.folder.zip)


https://www.loom.com/share/6524b47293c24f24816378a39dde25fe

**Comment by ankitguptaindia** [comment]
@amincdev 

**UX Suggestion -** Not a Bug but should be fixed for better UX.

No way to chage Privacy if user changed the mind Not to upload any Album and only want to add in root folder.

Please refer for steps to reproduce- https://www.loom.com/share/89aeed2c6c0e457e8d12bee05644caf3

**Comment by ankitguptaindia** [comment]
@amincdev 

Text area content should be clear after uploading Media. Currently old content still appear for new upload items.

https://www.loom.com/share/e9dcd9be32814b40b6d7e26872d33f67

-----

When Group does not have Any album and user is selcting Album then message is incomplate.

https://www.loom.com/share/661e950f936d4652bc1f573493bedb3b

-----

**Comment by ankitguptaindia** [comment]
@amincdev 

Issue with exicting functionality- Move to Folder doesn't work when clicking Read more Button on actvity.

https://www.loom.com/share/2858ad888b634f1a9493f1d8a4202ab0 

-----

UX Bug -  BACK button is not working intended . If user is not going to selct album and using BACK button to move back then it still uploading Media in that Album.


Refer -  https://www.loom.com/share/e0f58d420a674512b85e3f62354a10a7

-------

SUGGESTION -  Would be great if improve message for Group when group doesn't have any Album.
It shows - You have not created any album yet to move this photo into.
Is should be - You have not created any album in this Group yet to move this photo into.

Rfer-  https://www.loom.com/share/a2c82086b5af46dda751c716d40aee57

----

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> When uploading Media files to activity, it shows some unexpected reponse like object object in popup https://prnt.sc/vr7a66
> 
> I noticed it happens when I use .ico files in media.
> Attaching files with this comment so you can test on your site.
> 
> [untitled folder.zip](https://github.com/buddyboss/buddyboss-platform/files/5607817/untitled.folder.zip)
> 
> 
> https://www.loom.com/share/6524b47293c24f24816378a39dde25fe

@ankitguptaindia This is fixed now

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

Critical Scenario -  Rare to reproduce.

Refer my video for one by one steps.

https://www.loom.com/share/ffaacceb4d9547759572904ccf9a5c84

If user deleting Root Folder then subfolder are still appearing in Select Folder Popup. Technically those should also get deleted if user deleting main root folder.
As a result, if the user moving new files on those subfolders then uploaded files have no way to find. Those will invisible in a group.

In Popup- Numbers of folders appearing - https://prnt.sc/vsou31
Actaully folders avaible in group - https://prnt.sc/vsp0kd


-------

**Comment by ankitguptaindia** [comment]
@amincdev 

UX Issue -  Logic needs to be updated for Group-Specific Album popup.
It should show the respective Album selected when user uploading media from the album itself.

https://www.loom.com/share/6b2c83fa31ac488a84b812dce3101bd6

--------

Please add some margin between Select Album/Folder tab and photo thumbnail sams as design. https://prnt.sc/vsrkic

-----

Use Camel Case for these words https://www.loom.com/share/40525715675c4c109c55c570acb339a0

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

Issue when Group member moving photo to another album. user moves photo it shows you can not move as you don;t have permission for this BUT the user can delete photo easily.

If user is able to delete then user should also able to Move in albums.

Please refer for steps - https://www.loom.com/share/5a5ee74be223479c9981675ca7679655

**Comment by ankitguptaindia** [comment]
@amincdev 

When user uploads Media from Photos page and add description from text area. Old Content still appear after uploading the photo. This text area should auto clear once uploading done succesfully.

Refer for details - https://www.loom.com/share/be93d0ce0e9a492d96f5267ddca43028

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

Issue related to Privacy when moving Media files from one Album to Another Album. 
This is little complicated to reproduce. When moving Media from Public Album to Private Album then photo is still visible publicly.

Please follow steps shared in my video to reproduce.
FYI -  I am testing on `Dev` branch.  

https://www.loom.com/share/d1dd64312e314048ac9cfb479569d5f1

**Comment by ankitguptaindia** [comment]
@chetansatasiya / @amincdev 

Issue from Task List - 

>4. When you upload only 1 media/document and if you wriite any text then it should be added to that photo/document description

I tested this task on Dev branch and as well on respetive fix branch. But this is not wroking for me.

Refer - https://www.loom.com/share/a6215e555a914c4fa46cf2a4e0e86570

-------

**Comment by chetansatasiya** [comment]
> @chetansatasiya / @amincdev
> 
> Issue from Task List -
> 
> > 1. When you upload only 1 media/document and if you wriite any text then it should be added to that photo/document description
> 
> I tested this task on Dev branch and as well on respetive fix branch. But this is not wroking for me.
> 
> Refer -
> 
> https://www.loom.com/share/a6215e555a914c4fa46cf2a4e0e86570

@ankitguptaindia We reverted this changes and we are not implementing this as it's creating a issues in other places and also in actvity post form we have Editor and in media/document description edit we have a simple textarea.

**Comment by chetansatasiya** [comment]
> @chetansatasiya I found these 2 Critical Privacy bug and rare to reproduce if user moving files later by using the Move option available in More options.
> Although it is hard to reproduce easily. Sharing details below.
> 
> Support user has 1 root folder `Fol-1` and 4 subfolders like sub-1.... Sub-5 in that root folder. Fol-1 has Privacy `Only me` so as per logic all subfolders and files under Fol-1 will also have privacy Only me.
> 
> Suppose User Moved a file to directly to any subfolder then later change the privacy of that file from activity.
> When the user try to edit privacy system says - Edit Folder Privacy and open the popup to edit folder privacy.
> After that when user change the privacy of Subfolder-5 then it also change the privacy to all other subfolders like Sub-4, Sub-3 and root Folder Fol-1.
> 
> All files under root folder and subfolder getting public.
> 
> 
> https://www.loom.com/share/810a9b97b27b4b8898d3771697f897a4

@ankitguptaindia As we discussed in call techinacally it's 100% correct and working as expected. So if customer is changing intenionally then we don't do anything and we can't prevent this. CC: @sourabhmatolia

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> Critical Scenario - Rare to reproduce.
> 
> Refer my video for one by one step
> .
> 
> https://www.loom.com/share/ffaacceb4d9547759572904ccf9a5c84
> 
> If user deleting Root Folder then subfolder are still appearing in Select Folder Popup. Technically those should also get deleted if user deleting main root folder.
> As a result, if the user moving new files on those subfolders then uploaded files have no way to find. Those will invisible in a group.
> 
> In Popup- Numbers of folders appearing - https://prnt.sc/vsou31
> Actaully folders avaible in group - https://prnt.sc/vsp0kd

@ankitguptaindia Ican't reproduce this issue in my local with `dev` or `feature/media-document-enhancement` branch.

@ankitguptaindia can ask to check @mohit-buddyboss and @amincdev  to test this in their setup.

**Comment by chetansatasiya** [comment]
> SUGGESTION - Would be great if improve message for Group when group doesn't have any Album.
> It shows - You have not created any album yet to move this photo into.
> Is should be - You have not created any album in this Group yet to move this photo into.
> 
> Rfer-
> 
> https://www.loom.com/share/a2c82086b5af46dda751c716d40aee57

@ankitguptaindia This is done now 👍

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

Privacy issue when user moving Media from Activity timeline to Album. Private Photo appearing as public. 

When user moving Media from Timeline to Private Album and creating that Private Album at the time of moving the file via newly added create new album button then moved media appearing as public after moving in Private Album.
 
Refer this detailed video for details - 
https://www.loom.com/share/3564a6954be542489efbad88b4584542

**Comment by amincdev** [comment]
> > @chetansatasiya
> > Critical Scenario - Rare to reproduce.
> > Refer my video for one by one step
> > .
> > https://www.loom.com/share/ffaacceb4d9547759572904ccf9a5c84
> > If user deleting Root Folder then subfolder are still appearing in Select Folder Popup. Technically those should also get deleted if user deleting main root folder.
> > As a result, if the user moving new files on those subfolders then uploaded files have no way to find. Those will invisible in a group.
> > In Popup- Numbers of folders appearing - https://prnt.sc/vsou31
> > Actaully folders avaible in group - https://prnt.sc/vsp0kd
> 
> @ankitguptaindia Ican't reproduce this issue in my local with `dev` or `feature/media-document-enhancement` branch.
> 
> @ankitguptaindia can ask to check @mohit-buddyboss and @amincdev to test this in their setup.

@ankitguptaindia @chetansatasiya I'm also not able to reproduce:
https://www.loom.com/share/17cc89a8f6e74920b647854029c5df28

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

Media Privacy Issue - If we using this newly added moving features on new upload then its works fine but if we perform same on Old uploaded Media then nto working expected.

If media is uploaded recently then privacy is changing accordingly but if Media is uploaded a year ago and now user moving mediia to any private ALbum the this is accessible publically. 

https://www.loom.com/share/f50835bfab1743c39a1272ad12ffe51a

**Comment by amincdev** [comment]
@ankitguptaindia 

These issues have been fixed and merged in `dev`

1>
> Suggestion - If we add an option to delete albums from Album listing pages like we have added for delete photos and already have to delete documents then it would be easy to manage albums for users and will show consistency everywhere.
> https://www.loom.com/share/980cc4350c9540e59a62627ff9b472e7

**Created separate issue: https://github.com/buddyboss/buddyboss-platform/issues/1827**

2>
> Search box is missing for photos and album page.
> Although we have the same functionality on the global photos page. Users can search photos from global photos page but not from Member Profile and Gruop photos page.
> https://prnt.sc/vmn8cf
> https://prnt.sc/vmn968
> https://i.imgur.com/FLA21E0.jpg

**Create separate issue: https://github.com/buddyboss/buddyboss-platform/issues/1862**

3>
> Please correct or redo style for move and delete dropdown here:
> https://prnt.sc/vmwn42
> Make it consistent. Ask for a design from Bilal.

**Done - https://prnt.sc/vuxse8**

4>
> These newly added options are appearing out of image if image is small in size on Activity page.
> https://www.loom.com/share/67723c28c741438597cd972a88e9e73c
> Issue: https://prnt.sc/vo5h05

**Done - https://prnt.sc/vuxtiq**

5>
> When creating a new Album from popup then it is not an option to select privacy.
> I noticed it only happens when user select any already created album.
> This way it sounds like the user is going to create a sub album in any already created album that's why it is not giving privacy options because it will take privacy from main album.
> But we don't have a Sub Album feature.
> Please add conditions for this check. So it will always show Privacy option while creating new album from popup.
> More details
> https://www.loom.com/share/e9cd97560d0b4842a4f98b8580e1dc84

**Fixed - https://prnt.sc/vuxv10**

6>
> UX - If user already in any album and uploading new media then it should auto selected that album in popup.
> https://www.loom.com/share/594a205fd67647d1acbaa77686d87801

**Fixed - User will get album selected :  https://prnt.sc/vo7esb**

7>
> Suggestion - please set min value to 1. Right not it is taking -ve values.
> https://i.imgur.com/vOGhc5F.jpg

**Done**

8>
> Minor- Typo add space between File Size text
> https://i.imgur.com/1fTrWNd.jpg

**Fixed**

9>
> If user reached max number of photos/files then it should give:
> Proper detailed message like you can only upload max N number of file at a time instead of this incomplete message https://i.imgur.com/NRxLAWf.jpg
> If user crossed the limit per allowed per batch then it should not give uploader to upload next file.

**Fixed**

10>
> When user clicked delete icon without selecting any media then message need to style.
> https://i.imgur.com/XOqNqkZ.jpg

**Fixed - https://prnt.sc/vuxyrw**

11>
> Go to Photos in Profile > Select image using check icon > Click on Delete.
> It should show a standard "Are you sure" confirmation message before deleting.

**Fixed - https://prnt.sc/vuxzx5**

12>
> If User selected multiple photo and deleted only single photo by using individual option then it is deleting all photos. It should only delete all when user click delete icon available on right top.
> Please watch this video for better explanation
> https://www.loom.com/share/30cd4af1be724a17ac113e075dc5e536

**Fixed**

13>
> Media/Documents Uploader Popup issue - When user creates multiples Subfolders then the breadcrumb looks broken.
> https://prnt.sc/vqksy8

**Done - https://prnt.sc/vuy1u0**

14>
> Suggestions for UX - Destination folder should show as selected when user uploading documents to specific folders.
> Currently Its confusing bcoz users don't know in which folder documents going to upload.

**Done - https://prnt.sc/vuy2fv**

15>
> UX Suggestion - Not a Bug but should be fixed for better UX.
> No way to chage Privacy if user changed the mind Not to upload any Album and only want to add in root folder.
> Please refer for steps to reproduce-
> https://www.loom.com/share/89aeed2c6c0e457e8d12bee05644caf3

**- Back button is used to go back to first screen(To add/remove files, edit description, etc.) not to cancel album selection. To cancel album selection user can simply click on Album link in breadcrumb and then privacy dropdown will be back to normal check: https://prnt.sc/vsp68w**

16>
> Text area content should be clear after uploading Media. Currently old content still appear for new upload items.
> https://www.loom.com/share/e9dcd9be32814b40b6d7e26872d33f67

**Fixed**

17>
> When Group does not have Any album and user is selcting Album then message is incomplate.
> https://www.loom.com/share/661e950f936d4652bc1f573493bedb3b

**Fixed - https://prnt.sc/vuy3h8**

18>
> In Group when privacy dropdown is hidden done button should align with "Select Album"

**Done - https://prnt.sc/vuy4tr**

19>
> UX Bug - BACK button is not working intended . If user is not going to selct album and using BACK button to move back then it still uploading Media in that Album.
> https://www.loom.com/share/e0f58d420a674512b85e3f62354a10a7

**Back button is used to go back to first screen(To add/remove files, edit description, etc.) not to cancel album selection.**

20>
> UX Issue - Logic needs to be updated for Group-Specific Album popup.
> It should show the respective Album selected when user uploading media from the album itself.
> https://www.loom.com/share/6b2c83fa31ac488a84b812dce3101bd6/

**Done - https://prnt.sc/vuy4f8**

21>
> Please add some margin between Select Album/Folder tab and photo thumbnail sams as design. https://prnt.sc/vsrkic/

**Done - https://prnt.sc/vuyizp**

22>
> Use Camel Case for these words
> https://www.loom.com/share/40525715675c4c109c55c570acb339a0

**Done - https://prnt.sc/vuyk93**

23>
> When user uploads Media from Photos page and add description from text area. Old Content still appear after uploading the photo. This text area should auto clear once uploading done succesfully.
> https://www.loom.com/share/be93d0ce0e9a492d96f5267ddca43028/
> 

**Fixed**

24>
> Issue with exicting functionality- Move to Folder doesn't work when clicking Read more Button on actvity.
> https://www.loom.com/share/2858ad888b634f1a9493f1d8a4202ab0/

**Fixed**

**Comment by ankitguptaindia** [comment]
@amincdev 

Need to improve some user experience in uploader popup.

https://www.loom.com/share/23a60a1306e543b78af6cc6202b42da1

**Comment by amincdev** [comment]
> @amincdev
> 
> Need to improve some user experience in uploader popup.
> 
> 
> https://www.loom.com/share/23a60a1306e543b78af6cc6202b42da1

@ankitguptaindia This issue is fixed now
https://www.loom.com/share/a073b9f7fdb5460d88ed9272d9faf87e

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> Media Privacy Issue - If we using this newly added moving features on new upload then its works fine but if we perform same on Old uploaded Media then nto working expected.
> 
> If media is uploaded recently then privacy is changing accordingly but if Media is uploaded a year ago and now user moving mediia to any private ALbum the this is accessible publically.
> 
> 
> https://www.loom.com/share/f50835bfab1743c39a1272ad12ffe51a

@ankitguptaindia This is fixed now 👍

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> Privacy issue when user moving Media from Activity timeline to Album. Private Photo appearing as public.
> 
> When user moving Media from Timeline to Private Album and creating that Private Album at the time of moving the file via newly added create new album button then moved media appearing as public after moving in Private Album.
> 
> Refer this detailed video for details -
> 
> https://www.loom.com/share/3564a6954be542489efbad88b4584542

@ankitguptaindia This is fixed now 👍

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> Issue related to Privacy when moving Media files from one Album to Another Album.
> This is little complicated to reproduce. When moving Media from Public Album to Private Album then photo is still visible publicly.
> 
> Please follow steps shared in my video to reproduce.
> FYI - I am testing on `Dev` branch.
> 
> 
> https://www.loom.com/share/d1dd64312e314048ac9cfb479569d5f1

@ankitguptaindia This is fixed now 👍

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> Issue when Group member moving photo to another album. user moves photo it shows you can not move as you don;t have permission for this BUT the user can delete photo easily.
> 
> If user is able to delete then user should also able to Move in albums.
> 
> Please refer for steps -
> 
> https://www.loom.com/share/5a5ee74be223479c9981675ca7679655

@ankitguptaindia This is because of this https://github.com/buddyboss/buddyboss-platform/pull/1727 PR is merged in dev but the current logic is you can move or delete the document/photo only you uploaded and also you can't move the file to any other users folder.

@amincdev Please check this once if you need to work anything on design in spinner thing.

**Comment by chetansatasiya** [comment]
@ankitguptaindia All of issues are fixed and merged in dev. You can start on regression.

**Comment by amincdev** [comment]
> @chetansatasiya / @amincdev
> 
> Documents are not getting Moved to Folder if the folder is created from Popup.
> Although the folder is created successfully but Files are not appearing there after moving from Activity comments.
> Refer this video for more details-
> 
> https://www.loom.com/share/074a5ceea66a49ebb9579ab86d06138a
> 
> After moving Documents/Media to any folder/Album.
> Remaining Documents/Media having a blank sidebar.
> 
> 
> https://www.loom.com/share/4bf3591afdad454b9bf68a925c26bde6

1> This issue is now not replicable becuase we have already disabled move option for media/document in comment.
2> Same, There is no way to move media/document in comment. Also checked with activity media/document, It's working fine now.

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

>**Deleting a photo from newly added delete option breaking `Load More` button on Photos page.  https://i.imgur.com/zaqOorW.jpg**

NOT FIXED. Still facing this issue.👎 

Refer- https://www.loom.com/share/65ec4d8ffda64788b996a62632e996d4

**Comment by ankitguptaindia** [comment]
@chetansatasiya 

>Counts are not getting updated if deleting photos from newly added DELETE option.
https://www.loom.com/share/e7a4719ed240416ca6bdc7c0f25530a6

NOT FIXED. Still facing this issue.👎
Ref. https://www.loom.com/share/e958cfdd1bf74b40894c27f6775b5fc1

**Comment by ankitguptaindia** [comment]
> > @chetansatasiya / @amincdev
> > Documents are not getting Moved to Folder if the folder is created from Popup.
> > Although the folder is created successfully but Files are not appearing there after moving from Activity comments.
> > Refer this video for more details-
> > https://www.loom.com/share/074a5ceea66a49ebb9579ab86d06138a
> > After moving Documents/Media to any folder/Album.
> > Remaining Documents/Media having a blank sidebar.
> > https://www.loom.com/share/4bf3591afdad454b9bf68a925c26bde6
> 
> @ankitguptaindia
> 1> This issue is now not replicable becuase we have already disabled move option for media/document in comment.
> 2> Same, There is no way to move media/document in comment. Also checked with activity media/document, It's working fine now.



@amincdev this needs some more fixes.
1. More option tooltip is broken now
2. If we are not allowing to move comment files then would be great if we hide this option completely. 


Refer for more details - https://www.loom.com/share/7655efc87baf44a98021a3809cb7ce91

----

>@sourabhmatolia Inconsistency between photos and documents behavior. Please confirm if the current logic is intended.
**In documents, we are showing `More Options ` always and sub options according to File Owner. But for Media, We are showing `More Option` only when Media is uploaded by same user.**
Please refer for more details -  https://www.loom.com/share/44fd4f5372394b0188a13a4055dd39ff


Discussed over slack. It's okay and intended.

----


> **If any post has multiple images and the user removed any one image from the newly added option then that deleted image still appears in the popup when editing.**

And sometimes it shows a broken link with undefined. https://i.imgur.com/PpqAcsx.jpg 

Refer for steps, How to reproduce - https://www.loom.com/share/0c907558f7ac455b8c164c1315064ff8


**This is fixed now 👍** 

 
----

**Comment by chetansatasiya** [comment]
> @chetansatasiya
> 
> > Counts are not getting updated if deleting photos from newly added DELETE option.
> > https://www.loom.com/share/e7a4719ed240416ca6bdc7c0f25530a6
> 
> NOT FIXED. Still facing this issue.👎
> Ref.
> 
> https://www.loom.com/share/e958cfdd1bf74b40894c27f6775b5fc1

@ankitguptaindia This is fixed now and merged in dev 👍

**Comment by amincdev** [comment]
> > @chetansatasiya
> > Issue when Group member moving photo to another album. user moves photo it shows you can not move as you don;t have permission for this BUT the user can delete photo easily.
> > If user is able to delete then user should also able to Move in albums.
> > Please refer for steps -
> > https://www.loom.com/share/5a5ee74be223479c9981675ca7679655
> 
> @ankitguptaindia This is because of this #1727 PR is merged in dev but the current logic is you can move or delete the document/photo only you uploaded and also you can't move the file to any other users folder.
> 
> @amincdev Please check this once if you need to work anything on design in spinner thing.

@ankitguptaindia @chetansatasiya This seems fine now after Chetan's fix.

**Comment by amincdev** [comment]
@ankitguptaindia Here are the issues shared by @sourabhmatolia

- Profile > Documents > Move file always updates column order to name asc.
    **Fixed**
- Profile > Documents > Upload Files > Moved Folder and Create Folder > Create folder does not show indication of click.
Click indication should be there everywhere always.
    **Fixed**
- Profile > Photos > Upload Photo and Create Album > Create album click doesn't show click indication.
    **Fixed**
**Here’s explanation video for above 3 issues:** https://www.loom.com/share/672fe14a39b247259ecc36b79e1adf8f

- Profile > Documents > Order by Modified > Column icon is wrong after refresh. It's always acs order.
    **Fixed**
- Profile > Documents > IF I create folder with name "Global Folder !@#$%%^$#@" then create button load infinitely.
    **Working fine** Please let me know if you can replicate.
- Profile > Documents > When we are in root folder and upload then documents show instantly. But when we are in sub-folder then it doesn't.
     **Fixed**
- Profile > Documents > Create 5-6 level folders > Upload > See Layout issue: https://prnt.sc/vv7dd4 Works fine with Move folder action from the same folder. Show ellipsis (...)
    **Fixed - https://prnt.sc/vxio1c**
- Profile > Go to Single Album > Simply Click on delete and see layout issue: https://prnt.sc/vv7udo- Profile > Single Album > Click on delete > We should confirmation message before bulk deleting photos. Confirmation message should be everywhere.
    **Fixed**
- Same issue on Profile > Photos > Click on delete Show confirmation message here also on bulk delete.
    **Fixed**

**Comment by amincdev** [comment]
> > > @chetansatasiya / @amincdev
> > > Documents are not getting Moved to Folder if the folder is created from Popup.
> > > Although the folder is created successfully but Files are not appearing there after moving from Activity comments.
> > > Refer this video for more details-
> > > https://www.loom.com/share/074a5ceea66a49ebb9579ab86d06138a
> > > After moving Documents/Media to any folder/Album.
> > > Remaining Documents/Media having a blank sidebar.
> > > https://www.loom.com/share/4bf3591afdad454b9bf68a925c26bde6
> > 
> > 
> > @ankitguptaindia
> > 1> This issue is now not replicable becuase we have already disabled move option for media/document in comment.
> > 2> Same, There is no way to move media/document in comment. Also checked with activity media/document, It's working fine now.
> 
> @amincdev this needs some more fixes.
> 
> 1. More option tooltip is broken now
> 2. If we are not allowing to move comment files then would be great if we hide this option completely.
> 
> Refer for more details -
> 
> https://www.loom.com/share/7655efc87baf44a98021a3809cb7ce91

@ankitguptaindia 
I have added tooltip for disabled move option: https://prnt.sc/vy4ota
This issue is also fixed: https://prnt.sc/vy4poc

**Comment by ankitguptaindia** [comment]
@amincdev 

Seems youmissed this-  https://github.com/buddyboss/buddyboss-platform/issues/962#issuecomment-734329514 

>**UX issue -** If user uploading documents to folder which is appearing at the time of upload then it should not allow the user to Done until user selects the folder OR create a new folder. 
If user change mind not to upload in any specific folder then he/she should click `Back` button and click Done button.

https://www.loom.com/share/df1fca5cbd4247119dd8caa96b3f2ae0

This is still appearing same as previous.

**Comment by ankitguptaindia** [comment]
@amincdev 

Need some more improvment here if we can - 

>*Suggestions for UX - Destination folder should show as selected when user uploading documents to specific folders.**
Currently Its confusing bcoz users don't know in which folder documents going to upload.

Refer for more details - https://www.loom.com/share/e708610b3d3f41c5a778407d959a5396

Right now if folder has NO subfolder then it is appearing as selected but if user has any subfolders then it is still confusing.

https://www.loom.com/share/9d02a84f5ab145ff871576337a30eca6

**Comment by amincdev** [comment]
> @amincdev
> 
> Seems youmissed this- [#962 (comment)](https://github.com/buddyboss/buddyboss-platform/issues/962#issuecomment-734329514)
> 
> > **UX issue -** If user uploading documents to folder which is appearing at the time of upload then it should not allow the user to Done until user selects the folder OR create a new folder.
> > If user change mind not to upload in any specific folder then he/she should click `Back` button and click Done button.
> 
> 
> https://www.loom.com/share/df1fca5cbd4247119dd8caa96b3f2ae0
> 
> This is still appearing same as previous.

@ankitguptaindia I am not sure if we should include this in this PR or not. Maybe We can work on this as a separate task. @sourabhmatolia Please let us know what you suggest.

**Comment by ankitguptaindia** [comment]
@amincdev 

New issue - when user creating documents folder on the fly by using this new option added recently.
Spinner continuously running after creating the folder. User can not create new folder after that.

Refer  - https://www.loom.com/share/252c7ee3b18d49ebbe0228460068b197

**Comment by ankitguptaindia** [comment]
> > SUGGESTION - Would be great if improve message for Group when group doesn't have any Album.
> > It shows - You have not created any album yet to move this photo into.
> > Is should be - You have not created any album in this Group yet to move this photo into.
> > Rfer-
> > https://www.loom.com/share/a2c82086b5af46dda751c716d40aee57
> 
> @ankitguptaindia This is done now 👍



@chetansatasiya This fix is not working for me.

REfer - https://www.loom.com/share/1ba62c0dc70547a1a1f96c5807a35b41

**Comment by chetansatasiya** [comment]
> > > SUGGESTION - Would be great if improve message for Group when group doesn't have any Album.
> > > It shows - You have not created any album yet to move this photo into.
> > > Is should be - You have not created any album in this Group yet to move this photo into.
> > > Rfer-
> > > https://www.loom.com/share/a2c82086b5af46dda751c716d40aee57
> > 
> > 
> > @ankitguptaindia This is done now 👍
> 
> @chetansatasiya This fix is not working for me.
> 
> REfer -
> 
> https://www.loom.com/share/1ba62c0dc70547a1a1f96c5807a35b41

@ankitguptaindia I changed the text and now that text changes done by @sourabhmatolia so maybe that is final text.

**Comment by amincdev** [comment]
> @amincdev
> 
> New issue - when user creating documents folder on the fly by using this new option added recently.
> Spinner continuously running after creating the folder. User can not create new folder after that.
> 
> Refer -
> 
> https://www.loom.com/share/252c7ee3b18d49ebbe0228460068b197

@ankitguptaindia I checked in document and photos and it is working fine now. Can you please check?

**Comment by ankitguptaindia** [comment]
@amincdev @chetansatasiya 

>**If any post has multiple images and the user removed any one image from the newly added option then that deleted image still appears in the popup when editing.**
And sometimes it shows a broken link with undefined. https://i.imgur.com/PpqAcsx.jpg 
Refer for steps, How to reproduce - https://www.loom.com/share/0c907558f7ac455b8c164c1315064ff8


**This is fixed now 👍** 


----------------
-----


> **Deleting a photo from newly added delete option breaking `Load More` button on Photos page.  https://i.imgur.com/zaqOorW.jpg**

NOT FIXED.  @amincdev 
Refer- https://www.loom.com/share/65ec4d8ffda64788b996a62632e996d4

---------


>Counts are not getting updated if deleting photos from newly added DELETE option.
https://www.loom.com/share/e7a4719ed240416ca6bdc7c0f25530a6

**Fixed.**
https://www.loom.com/share/e958cfdd1bf74b40894c27f6775b5fc1 

----


>@sourabhmatolia Inconsistency between photos and documents behavior. Please confirm if the current logic is intended.
**In documents, we are showing `More Options ` always and sub options according to File Owner. But for Media, We are showing `More Option` only when Media is uploaded by same user.**
Please refer for more details -  https://www.loom.com/share/44fd4f5372394b0188a13a4055dd39ff


Discussed over slack. Its intended. 

----



>Documents are not getting Moved to Folder if the folder is created from Popup. 
Although the folder is created successfully but Files are not appearing there after moving from Activity comments.
Refer this video for more details- 
https://www.loom.com/share/074a5ceea66a49ebb9579ab86d06138a

Documents/Media move support has been removed from Comments area. 

----

>After moving Documents/Media to any folder/Album.
Remaining  Documents/Media having a blank sidebar.
https://www.loom.com/share/4bf3591afdad454b9bf68a925c26bde6

FIXED.
----


>Please style this message box when uploading documents in User's Documents area.
https://prnt.sc/vqka2u

**DONE.**
----

>**UX issue -** If user uploading documents to folder which is appearing at the time of upload then it should not allow the user to Done until user selects the folder OR create a new folder. 
If user change mind not to upload in any specific folder then he/she should click `Back` button and click Done button.
https://www.loom.com/share/df1fca5cbd4247119dd8caa96b3f2ae0

Will work on this in saparte PR as suggesdte dby dev here. https://github.com/buddyboss/buddyboss-platform/issues/962#issuecomment-741732837
https://github.com/buddyboss/buddyboss-platform/issues/962#issuecomment-734329514 

-----

>**Media/Documents Uploader Popup issue -  When user creates multiples Subfolders then the breadcrumb looks broken.**
https://prnt.sc/vqksy8

**Fixed.**

------

>**Suggestions for UX - Destination folder should show as selected when user uploading documents to specific folders.**
Currently Its confusing bcoz users don't know in which folder documents going to upload.
Refer for more details - https://www.loom.com/share/e708610b3d3f41c5a778407d959a5396


As discussed with Amin over Salck. wehave followed logic same as Dropbox here.


-------



>@chetansatasiya  I found these 2 Critical Privacy bug and rare to reproduce if user moving files later by using the Move option available in More options.
Although it is hard to reproduce easily. Sharing details below.
Support user has 1 root folder `Fol-1` and 4 subfolders like sub-1.... Sub-5 in that root folder. Fol-1 has Privacy `Only me` so as per logic all subfolders and files under Fol-1 will also have privacy Only me.
Suppose User Moved a file to directly to any subfolder then later change the privacy of that file from activity.
When the user try to edit privacy system says - Edit Folder Privacy and open the popup to edit folder privacy.
After that when user change the privacy of Subfolder-5 then it also change the privacy to all other subfolders like Sub-4, Sub-3 and root Folder Fol-1.
All files under root folder and subfolder getting public.
https://www.loom.com/share/810a9b97b27b4b8898d3771697f897a4

As per discussion with dev. it is okay.
https://github.com/buddyboss/buddyboss-platform/issues/962#issuecomment-737003117

---

>@chetansatasiya 
When uploading Media files to activity, it shows some unexpected reponse like object object in popup https://prnt.sc/vr7a66 
I noticed it happens when I use .ico files in media. 
Attaching files with this comment so you can test on your site.
[untitled folder.zip](https://github.com/buddyboss/buddyboss-platform/files/5607817/untitled.folder.zip)
https://www.loom.com/share/6524b47293c24f24816378a39dde25fe

**FIXED**

----


>**UX Suggestion -** Not a Bug but should be fixed for better UX.
No way to chage Privacy if user changed the mind Not to upload any Album and only want to add in root folder.
Please refer for steps to reproduce- https://www.loom.com/share/89aeed2c6c0e457e8d12bee05644caf3 


 **it's okay. Added details by dev here - 
>- Back button is used to go back to first screen(To add/remove files, edit description, etc.) not to cancel album selection. To cancel album selection user can simply click on Album link in breadcrumb and then privacy dropdown will be back to normal check: https://prnt.sc/vsp68w

-----



>Text area content should be clear after uploading Media. Currently old content still appear for new upload items.
https://www.loom.com/share/e9dcd9be32814b40b6d7e26872d33f67

**Fixed.** 

-----

>When Group does not have Any album and user is selcting Album then message is incomplate.
https://www.loom.com/share/661e950f936d4652bc1f573493bedb3b 

FIXED.

-----


>Issue with exicting functionality- Move to Folder doesn't work when clicking Read more Button on actvity.
https://www.loom.com/share/2858ad888b634f1a9493f1d8a4202ab0 

**FIXED>**

-----

UX Bug -  BACK button is not working intended . If user is not going to selct album and using BACK button to move back then it still uploading Media in that Album.
Refer -  https://www.loom.com/share/e0f58d420a674512b85e3f62354a10a7

**Okay then.**

-------

>SUGGESTION -  Would be great if improve message for Group when group doesn't have any Album.
It shows - You have not created any album yet to move this photo into.
Is should be - You have not created any album in this Group yet to move this photo into.
Rfer-  https://www.loom.com/share/a2c82086b5af46dda751c716d40aee57

Discussed here https://github.com/buddyboss/buddyboss-platform/issues/962#issuecomment-741841322

----

>Critical Scenario -  Rare to reproduce.
Refer my video for one by one step
.https://www.loom.com/share/ffaacceb4d9547759572904ccf9a5c84
If user deleting Root Folder then subfolder are still appearing in Select Folder Popup. Technically those should also get deleted if user deleting main root folder.
As a result, if the user moving new files on those subfolders then uploaded files have no way to find. Those will invisible in a group.
In Popup- Numbers of folders appearing - https://prnt.sc/vsou31
Actaully folders avaible in group - https://prnt.sc/vsp0kd


**This is working for Chetan and Amin. Tried to other setup but unable to reproduce. will check later if someone facing this issue.**

-------

>UX Issue -  Logic needs to be updated for Group-Specific Album popup.
It should show the respective Album selected when user uploading media from the album itself.
https://www.loom.com/share/6b2c83fa31ac488a84b812dce3101bd6

**Fixed.**

--------

>Please add some margin between Select Album/Folder tab and photo thumbnail sams as design. https://prnt.sc/vsrkic

**FIXED>**

-----

>Use Camel Case for these words https://www.loom.com/share/40525715675c4c109c55c570acb339a0


**FIXED>** 

----


>Issue when Group member moving photo to another album. user moves photo it shows you can not move as you don;t have permission for this BUT the user can delete photo easily.
If user is able to delete then user should also able to Move in albums.
Please refer for steps - https://www.loom.com/share/5a5ee74be223479c9981675ca7679655


Okay. then Chetan's comment https://github.com/buddyboss/buddyboss-platform/issues/962#issuecomment-739244673


-------

>When user uploads Media from Photos page and add description from text area. Old Content still appear after uploading the photo. This text area should auto clear once uploading done succesfully.
Refer for details - https://www.loom.com/share/be93d0ce0e9a492d96f5267ddca43028


FIXED.
-----

>Issue related to Privacy when moving Media files from one Album to Another Album. 
This is little complicated to reproduce. When moving Media from Public Album to Private Album then photo is still visible publicly.
Please follow steps shared in my video to reproduce.
FYI -  I am testing on `Dev` branch.  
https://www.loom.com/share/d1dd64312e314048ac9cfb479569d5f1

**FIXED>**

----

>Issue from Task List - 

>4. When you upload only 1 media/document and if you wriite any text then it should be added to that photo/document description
I tested this task on Dev branch and as well on respetive fix branch. But this is not wroking for me.
Refer - https://www.loom.com/share/a6215e555a914c4fa46cf2a4e0e86570

This has been reverted  https://github.com/buddyboss/buddyboss-platform/issues/962#issuecomment-737001320


-------


>Privacy issue when user moving Media from Activity timeline to Album. Private Photo appearing as public. 
When user moving Media from Timeline to Private Album and creating that Private Album at the time of moving the file via newly added create new album button then moved media appearing as public after moving in Private Album.
 Refer this detailed video for details - 
https://www.loom.com/share/3564a6954be542489efbad88b4584542

**FIXED.**

-----


>Media Privacy Issue - If we using this newly added moving features on new upload then its works fine but if we perform same on Old uploaded Media then nto working expected.
If media is uploaded recently then privacy is changing accordingly but if Media is uploaded a year ago and now user moving mediia to any private ALbum the this is accessible publically. 

https://www.loom.com/share/f50835bfab1743c39a1272ad12ffe51a

**Fixed.**

------


>@amincdev 
Need to improve some user experience in uploader popup.
https://www.loom.com/share/23a60a1306e543b78af6cc6202b42da1

**FIXED.**

**Comment by ankitguptaindia** [comment]
@amincdev 
Issue reported by @sourabhmatolia 

>Profile > Documents > IF I create folder with name "Global Folder !@#$%%^$#@" then create button load infinitely.
Working fine Please let me know if you can replicate.

and issues reported by me:
 
>New issue - when user creating documents folder on the fly by using this new option added recently.
Spinner continuously running after creating the folder. User can not create new folder after that.
Refer - https://www.loom.com/share/252c7ee3b18d49ebbe0228460068b197

Both are replicateable to me and looks similer. Please check.

**Comment by ankitguptaindia** [comment]
Status of issues reported by @sourabhmatolia 

- Profile > Documents > Move file always updates column order to name asc.
    **Fixed**
- Profile > Documents > Upload Files > Moved Folder and Create Folder > Create folder does not show indication of click.
Click indication should be there everywhere always.
    **Fixed**
- Profile > Photos > Upload Photo and Create Album > Create album click doesn't show click indication.
    **Fixed**
**Here’s explanation video for above 3 issues:** https://www.loom.com/share/672fe14a39b247259ecc36b79e1adf8f

- Profile > Documents > Order by Modified > Column icon is wrong after refresh. It's always acs order.
    **Fixed**
- Profile > Documents > IF I create folder with name "Global Folder !@#$%%^$#@" then create button load infinitely.
   
Updated details in the previous comment.

- Profile > Documents > When we are in root folder and upload then documents show instantly. But when we are in sub-folder then it doesn't.
     **Fixed**
- Profile > Documents > Create 5-6 level folders > Upload > See Layout issue: https://prnt.sc/vv7dd4 Works fine with Move folder action from the same folder. Show ellipsis (...)
    **Fixed - https://prnt.sc/vxio1c**
- Profile > Go to Single Album > Simply Click on delete and see layout issue: https://prnt.sc/vv7udo- Profile > Single Album > Click on delete > We should confirmation message before bulk deleting photos. Confirmation message should be everywhere.
    **Fixed**
- Same issue on Profile > Photos > Click on delete Show confirmation message here also on bulk delete.
    **Fixed**

**Comment by amincdev** [comment]
> @amincdev
> Issue reported by @sourabhmatolia
> 
> > Profile > Documents > IF I create folder with name "Global Folder !@#$%%^$#@" then create button load infinitely.
> > Working fine Please let me know if you can replicate.
> 
> and issues reported by me:
> 
> > New issue - when user creating documents folder on the fly by using this new option added recently.
> > Spinner continuously running after creating the folder. User can not create new folder after that.
> > Refer - https://www.loom.com/share/252c7ee3b18d49ebbe0228460068b197
> 
> Both are replicateable to me and looks similer. Please check.

@ankitguptaindia This issue is fixed now. Can you please check:
Proof: https://www.loom.com/share/b713b9b09598463e81fb2b53b2b58bfc

**Comment by ankitguptaindia** [comment]
> > @amincdev
> > Issue reported by @sourabhmatolia
> > > Profile > Documents > IF I create folder with name "Global Folder !@#$%%^$#@" then create button load infinitely.
> > > Working fine Please let me know if you can replicate.
> > 
> > 
> > and issues reported by me:
> > > New issue - when user creating documents folder on the fly by using this new option added recently.
> > > Spinner continuously running after creating the folder. User can not create new folder after that.
> > > Refer - https://www.loom.com/share/252c7ee3b18d49ebbe0228460068b197
> > 
> > 
> > Both are replicateable to me and looks similer. Please check.
> 
> @ankitguptaindia This issue is fixed now. Can you please check:
> Proof: https://www.loom.com/share/b713b9b09598463e81fb2b53b2b58bfc


@amincdev I can still able to see these issues on my site.
Refer -  https://www.loom.com/share/e1be0aa435d54cacb7607899b92f101e

If you want to debug on my site. let me know I will provide my local DB to you then.

**Comment by amincdev** [comment]
@ankitguptaindia This issue is fixed now, Can you please check?
proof: https://prnt.sc/w2y9t9

**Comment by ankitguptaindia** [comment]
> @ankitguptaindia This issue is fixed now, Can you please check?
> proof: https://prnt.sc/w2y9t9

@amincdev Thanks. Those issues are fixed now.
